# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18b215cf4770c560100f057b8d58769d7c6ab543d050a01ab4928d9aac0d87e93f35b9b4d88e053d8bd7adf51d09ef5c307f109482757db582b07d714b148da1

test:
  secret_key_base: d1f5f57b18130d152951b79e376adb7a6d1675ba34d5109905b3041bb402394ca5d559f1a8c1e60e7377937451e52c9a4d1d13a41d3a2e59048c180fe29cc1b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
